%YAML:1.0


image_topic: "/cam1/image_raw"
output_path: "/home/yhr/output"
#camera calibration 
model_type: PINHOLE
camera_name: camera
width: 752
height: 480
distortion_parameters:
   k1: -2.837e-01
   k2: 7.451e-02
   p1: 1.047e-04
   p2: -3.556e-05
projection_parameters:
   fx: 4.576e+02
   fy: 4.561e+02
   cx: 3.800e+02
   cy: 2.552e+02

   
#additional transform for bais
initialRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   # data: [1, 0, 0,
   #        0, 1, 0,
   #        0, 0, 1]
   data: [0.9994,   -0.0344,   -0.0073,
          0.0344,    0.9994,    0.0023,
          0.0072,   -0.0026,    1.0000]

#Translation from first body frame to world frame
initialTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   # data: [0.0, 0.0, 0.0]
   data: [0.1118, -0.0142, -0.0401]

   
# Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.0125552670891, -0.999755099723, 0.0182237714554,
           0.999598781151, 0.0130119051815, 0.0251588363115, 
           -0.0253898008918, 0.0179005838253, 0.999517347078]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-0.0198435579556,0.0453689425024, 0.00786212447038]

# optimization parameters
iterations: 2
per_inliers: 7
savefile: 0
threshold: 30
lamda: 0.1745 #0.1745
show: 1

